# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Cangol
description:      'Can go anywhere, if i want to'
url:              http://cangol.mobi
baseurl:          /
logo:             /content/images/me.jpeg

author:
  name:           'Cangol'
  url:            https://plus.google.com/+ChrisBanes

paginate:         5

disqus_shortname: Cangol

github:
  repo:           https://github.com/Cangol

gems:
  - jekyll-sitemap

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
