# Dependencies
markdown:         redcarpet
highlighter:      pygments
redcarpet:
<<<<<<< HEAD
    extensions: [ "fenced_code_blocks", "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]

=======
  extensions: [ "fenced_code_blocks", "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
>>>>>>> 3eabe6bd05cdcc229d165444f51198041e83eac9
# Permalinks
permalink:        pretty

# Setup
title:            Cangol
description:      'Can go anywhere, if i want to'
url:              http://cangol.mobi
baseurl:          /
logo:             /content/images/me.jpeg

author:
  name:           'Cangol'
  url:            https://plus.google.com/+Cangol

paginate:         10

disqus_shortname: Cangol

github:
  repo:           https://github.com/Cangol

gems:
  - jekyll-sitemap

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
