# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Chris Banes
tagline:          'A Jekyll theme'
description:      'I work as a DPE in the Android Developer Relations team. This is my personal blog and any views expressed here are mine, and not my employers.'
url:              http://chris.banes.me
baseurl:          /
logo:             /content/images/me.jpg

author:
  name:           'Chris Banes'
  url:            https://plus.google.com/+ChrisBanes

paginate:         5

disqus_shortname: chrisbanes

github:
  repo:           https://github.com/chrisbanes/chrisbanes.github.io
